'''
Project Euler
Problem 2
2/14/2021

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''


def even_fibonacci_generator(upper_bound):
    last, current = 1, 2
    while current < upper_bound:
        yield current
        last, current = last + 2 * current, 2 * last + 3 * current


def solution(upper_bound):
    return sum(even_fibonacci_generator(upper_bound))


assert(solution(100) == sum([2, 8, 34]))
print(solution(4e6))
